/**
 * The front door — the only process this deployment exposes to the internet.
 *
 * `cloudflared` points here and nowhere else. Vite preview and, in a later
 * phase, every rendering instance bind to loopback. That is the whole point of
 * the shape: upstream's dev/preview middleware (`/dev-proxy`, an arbitrary
 * fetch relay; `/__play`, which spawns mpv; `/__feedback`, which writes files)
 * ships live in `npm run serve`, which is what Docker and systemd actually run.
 * Rather than trying to gate those routes, this design makes them unreachable
 * — you cannot forget to protect a port you never published.
 *
 * WHAT IT DOES
 *   GET  /healthz              liveness, unauthenticated by design
 *   POST /auth/pin             begin Plex sign-in, returns a code + auth URL
 *   POST /auth/claim           exchange an authorised pin for a session cookie
 *   POST /auth/signout         drop this session
 *   GET  /api/me               who am I, and am I the owner
 *   GET  /api/config           this viewer's store settings
 *   PUT  /api/config           write one setting, owner rules enforced here
 *   *                          the store app, behind the gate
 *
 * Phase 1 of docs/architecture/2026-09-06-plex-only-streaming-fork.md. The
 * instance pool (Phase 2) attaches at `requireSession` — it is the thing that
 * turns a session into a rendering instance.
 */

import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { randomUUID, timingSafeEqual } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { loadConfig, type FrontDoorConfig } from './config.ts';
import { FrontDoorStore } from './store.ts';
import { signSession, verifySession, type SessionPayload } from './sessions.ts';
import { grantsAccessTo, isOwnerOf } from './plex-gate.ts';
import { createPin, claimPin, fetchAccount, fetchResources, type PlexClientIdentity } from './plex-client.ts';
import { assertWritable } from './owner-keys.ts';
import { signInPage, signedInPage } from './signin-page.ts';
import { proxyToApp } from './app-proxy.ts';
import { setupPage } from './setup-page.ts';
import { connectionForViewer, connectionBootstrapScript, type StoreConnection } from './plex-connection.ts';
import { loadPolicy, policyKeys } from './admin-config.ts';
import { startAdminServer } from './admin.ts';
import { saveInstance, isConfigured, type InstanceSecrets } from './bootstrap.ts';

const COOKIE = 'hv_session';

const PIN_TTL_MS = 10 * 60_000;
const PIN_RATE_WINDOW_MS = 10 * 60_000;
const PIN_RATE_MAX = 10;

/**
 * Who is calling, for rate-limiting purposes.
 *
 * `CF-Connecting-IP` is only trusted when TRUST_PROXY_HEADERS says a proxy is
 * genuinely in front, and the default is NOT to trust it.
 *
 * The reasoning runs the opposite way to the obvious one. An attacker who can
 * set that header freely does not merely evade the limit — they get an
 * unlimited number of distinct buckets by sending a different value each time,
 * which is strictly worse than having no per-caller limit at all. A limiter
 * keyed on something forgeable is an illusion of one.
 *
 * Falling back to the socket address behind a tunnel means every caller shares
 * one bucket, so the limit becomes global rather than per-IP. That is a real
 * cost — one noisy client can use up everyone's allowance — but it fails
 * closed and is honest about what it is, which a spoofable key is not.
 *
 * Set TRUST_PROXY_HEADERS=1 only when nothing but the proxy can reach this
 * port, which is exactly the case behind cloudflared with the service bound to
 * loopback or inside a container network.
 */
function callerKey(req: IncomingMessage): string {
  // Read per call rather than cached at module load, so a test can exercise
  // both postures in one process. The cost is one env lookup on an endpoint
  // that is already making a network request to plex.tv.
  if (process.env.TRUST_PROXY_HEADERS === '1') {
    const cf = req.headers['cf-connecting-ip'];
    if (typeof cf === 'string' && cf) return cf.split(',')[0].trim();
    const xff = req.headers['x-forwarded-for'];
    const first = Array.isArray(xff) ? xff[0] : xff;
    if (typeof first === 'string' && first) return first.split(',')[0].trim();
  }
  return req.socket.remoteAddress || 'unknown';
}

/** The bundled display face, self-hosted — never fetched from Google. */
let fontCache: Buffer | null = null;
function archivoBlack(): Buffer | null {
  if (fontCache) return fontCache;
  try {
    fontCache = readFileSync(new URL('../src/assets/archivo-black.ttf', import.meta.url));
    return fontCache;
  } catch {
    // The page falls back to Arial Black. A missing font is a cosmetic
    // problem, never a reason to fail a sign-in.
    return null;
  }
}

/**
 * The social card, generated by tools/gen-share-image.mjs into public/ — which
 * is in the image (see .dockerignore's whitelist) and is also what Vite copies
 * into dist/, so one file serves both the front door and a directly-run store.
 */
let cardCache: Buffer | null = null;
function shareCard(): Buffer | null {
  if (cardCache) return cardCache;
  try {
    cardCache = readFileSync(new URL('../public/share/volkbuster-share.png', import.meta.url));
    return cardCache;
  } catch {
    // No card is a missing preview, never a failed sign-in.
    return null;
  }
}

function html(res: ServerResponse, status: number, body: string): void {
  res.writeHead(status, {
    'content-type': 'text/html; charset=utf-8',
    'content-length': Buffer.byteLength(body),
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'DENY',
    'referrer-policy': 'no-referrer',
    // The page talks to itself and, by opening a link, to plex.tv. Nothing else.
    'content-security-policy':
      "default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; "
      + "font-src 'self'; img-src 'self' data:; connect-src 'self'; form-action 'self'; "
      + "base-uri 'none'; frame-ancestors 'none'",
    'cache-control': 'no-store',
  });
  res.end(body);
}

// ─── HTTP helpers ────────────────────────────────────────────────────────────

function json(res: ServerResponse, status: number, body: unknown): void {
  const payload = JSON.stringify(body);
  res.writeHead(status, {
    'content-type': 'application/json; charset=utf-8',
    'content-length': Buffer.byteLength(payload),
    // This is an API for our own page; nothing should frame it or sniff it.
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'DENY',
    'referrer-policy': 'no-referrer',
  });
  res.end(payload);
}

function readCookie(req: IncomingMessage, name: string): string | null {
  const header = req.headers.cookie;
  if (!header) return null;
  for (const part of header.split(';')) {
    const eq = part.indexOf('=');
    if (eq < 0) continue;
    if (part.slice(0, eq).trim() === name) return decodeURIComponent(part.slice(eq + 1).trim());
  }
  return null;
}

/**
 * Is this request actually running over TLS?
 *
 * `Secure` used to be unconditional here, on the reasoning that the only way in
 * was an HTTPS tunnel. That was wrong, and it produced an infinite sign-in
 * loop: over plain HTTP on a LAN address the browser SILENTLY DISCARDS a Secure
 * cookie, so authentication succeeded server-side, the cookie never survived,
 * and the next request arrived with no session — back to the sign-in page,
 * forever, with nothing in any log to say why.
 *
 * (http://localhost is exempt in browsers, which is why it never showed up in
 * local testing. http://192.168.x.x is not.)
 *
 * `x-forwarded-proto` first, because behind cloudflared or any reverse proxy
 * the connection to this process is plain HTTP even though the viewer's is
 * HTTPS — trusting the socket alone would drop Secure on exactly the deployment
 * that needs it most.
 */
function isSecureRequest(req: IncomingMessage): boolean {
  const header = req.headers['x-forwarded-proto'];
  const proto = Array.isArray(header) ? header[0] : header;
  // A chain of proxies appends, so the ORIGINAL scheme is the first entry.
  if (typeof proto === 'string' && proto.length) {
    return proto.split(',')[0].trim().toLowerCase() === 'https';
  }
  return Boolean((req.socket as { encrypted?: boolean }).encrypted);
}

/**
 * The public origin this request arrived at, or '' if it cannot be trusted.
 *
 * Needed for the link-preview card: og:image must be an ABSOLUTE URL (Twitter
 * and iMessage ignore a relative one), and this process cannot know its own
 * public name — behind cloudflared the tunnel terminates elsewhere and the
 * socket only ever sees 127.0.0.1.
 *
 * SO IT COMES FROM THE HOST HEADER, which is attacker-controlled, and that is
 * the whole reason for the allowlist below. A host is accepted only if it
 * looks like a hostname or an IP with an optional port — no slashes, no
 * spaces, no quotes, nothing that could carry a path or break out of the
 * attribute it lands in. A rejected host yields '' and the page simply ships
 * without a card, which is a cosmetic loss and never a broken page.
 *
 * The consequence of a forged Host is that someone who can already reach this
 * port makes their OWN preview point at their own hostname. There is nothing
 * to steal there: the image is public and the page it decorates is the login
 * screen. The escaping is what matters, and it is unconditional.
 */
const SAFE_HOST = /^[a-z0-9.-]{1,253}(:\d{1,5})?$|^\[[0-9a-f:]{2,45}\](:\d{1,5})?$/i;
function publicOrigin(req: IncomingMessage): string {
  const raw = req.headers.host;
  const host = Array.isArray(raw) ? raw[0] : raw;
  if (!host || !SAFE_HOST.test(host)) return '';
  return `${isSecureRequest(req) ? 'https' : 'http'}://${host}`;
}

/**
 * `SameSite=Lax` rather than Strict: the Plex sign-in sends the viewer to
 * app.plex.tv and back, and Strict would withhold the cookie on that return
 * navigation, so a freshly signed-in viewer would land looking signed out.
 */
function cookieAttrs(req: IncomingMessage): string {
  return `HttpOnly;${isSecureRequest(req) ? ' Secure;' : ''} SameSite=Lax; Path=/`;
}

function setSessionCookie(req: IncomingMessage, res: ServerResponse, token: string, maxAgeMs: number): void {
  res.setHeader('set-cookie',
    `${COOKIE}=${encodeURIComponent(token)}; ${cookieAttrs(req)}; Max-Age=${Math.floor(maxAgeMs / 1000)}`);
}

function clearSessionCookie(req: IncomingMessage, res: ServerResponse): void {
  res.setHeader('set-cookie', `${COOKIE}=; ${cookieAttrs(req)}; Max-Age=0`);
}

async function readJsonBody(req: IncomingMessage, limitBytes = 64 * 1024): Promise<unknown> {
  const chunks: Buffer[] = [];
  let total = 0;
  for await (const chunk of req) {
    total += (chunk as Buffer).length;
    // A body limit is not optional on a public endpoint: without it, one
    // request can exhaust the process's memory.
    if (total > limitBytes) throw new Error('request body too large');
    chunks.push(chunk as Buffer);
  }
  if (!chunks.length) return {};
  return JSON.parse(Buffer.concat(chunks).toString('utf8'));
}

// ─── The service ─────────────────────────────────────────────────────────────

export function createFrontDoor(
  cfg: FrontDoorConfig,
  db: FrontDoorStore,
  now: () => number = Date.now,
  instance?: InstanceSecrets,
) {
  /**
   * First-run state. Held in a closure so a test can drive setup without
   * touching disk, and mutated in place when setup completes so the running
   * process starts gating immediately rather than needing a restart.
   */
  const inst: InstanceSecrets = instance ?? {
    sessionSecret: cfg.sessionSecret,
    tokenKey: '',
    setupToken: null,
    plexMachineId: cfg.plexMachineId || null,
    plexClientId: process.env.PLEX_CLIENT_ID || 'volkbuster-front-door',
  };
  /**
   * Resolved Plex connections, per session.
   *
   * Resolving one costs a plex.tv round trip, and it is needed on every
   * document load. Without a cache a viewer walking around the store would
   * re-query plex.tv on each navigation, which is slow for them and rude to
   * Plex. Short-lived so a server address that changes — a new LAN IP, relay
   * coming or going — is picked up without a sign-out.
   */
  const connCache = new Map<string, { conn: StoreConnection | null; at: number }>();
  const CONN_TTL_MS = 10 * 60_000;

  async function connectionFor(sid: string, viewerToken: string): Promise<StoreConnection | null> {
    const hit = connCache.get(sid);
    if (hit && now() - hit.at < CONN_TTL_MS) return hit.conn;
    const conn = await connectionForViewer(viewerToken, cfg.plexMachineId, identity);
    connCache.set(sid, { conn, at: now() });
    return conn;
  }

  /** Cleared once a setup code is accepted, so the code is single-use. */
  let setupClaimed = false;
  /** The Plex token of whoever is completing setup, held only until they pick. */
  let setupToken: string | null = null;
  /**
   * Sign-in state belongs to THIS front door, not to the module.
   *
   * Module-level maps would be shared by every instance in a process — which
   * makes two servers silently share a rate-limit budget and a pin table, and
   * makes them untestable in isolation (the second test in a file inherits the
   * first one's exhausted limiter). Per-instance is both the correct scope and
   * the testable one.
   *
   * In memory rather than in SQLite on purpose: a pin is worthless the moment
   * it is claimed, and a restart mid-sign-in just means signing in again.
   */
  const pendingPins = new Map<number, { createdAt: number }>();
  const pinAttempts = new Map<string, number[]>();

  /**
   * Per-caller rate limit on `/auth/pin` — the one endpoint that is both
   * unauthenticated and reaches out to plex.tv on a stranger's say-so.
   *
   * Without it, anyone who can load the sign-in page can make this server
   * hammer plex.tv, and can exhaust the shared pending-pin table for everybody
   * else. A global cap alone does not help: it is a shared resource, so one
   * caller filling it is a denial of service against real viewers.
   */
  function rateLimited(req: IncomingMessage, at: number): boolean {
    const key = callerKey(req);
    const hits = (pinAttempts.get(key) || []).filter((t) => at - t < PIN_RATE_WINDOW_MS);
    hits.push(at);
    pinAttempts.set(key, hits);
    // Keep the map bounded on a long-lived process.
    if (pinAttempts.size > 5000) {
      for (const [k, v] of pinAttempts) {
        if (!v.some((t) => at - t < PIN_RATE_WINDOW_MS)) pinAttempts.delete(k);
      }
    }
    return hits.length > PIN_RATE_MAX;
  }

  const identity: PlexClientIdentity = {
    // Stable per install. See plex-client.ts — Plex keys session eviction off
    // this, so it is read from config and only generated once.
    clientId: process.env.PLEX_CLIENT_ID || inst.plexClientId,
    product: process.env.PLEX_PRODUCT || 'VolkBuster Video',
    version: '0.15.0',
    device: 'VolkBuster Front Door',
    platform: 'Node',
  };

  /**
   * Resolve the caller's session, or null.
   *
   * Two layers, and both are needed. The cookie proves the session was minted
   * here and has not expired. The database lookup proves it has not since been
   * revoked — a signature alone cannot express "the owner unshared this person
   * ten minutes ago", because the token was already signed before that
   * happened.
   */
  function currentSession(req: IncomingMessage): { payload: SessionPayload; token: string } | null {
    const raw = readCookie(req, COOKIE);
    if (!raw) return null;
    const payload = verifySession(raw, cfg.sessionSecret, now());
    if (!payload) return null;
    const stored = db.getSession(payload.sid);
    if (!stored) return null;
    return { payload, token: stored.token };
  }

  /**
   * Re-check a live session against Plex sharing, at most once per
   * `revalidateAfterMs`.
   *
   * Without this, revocation only takes effect when the session expires — up to
   * a month later. With it, unsharing a library removes access within a day,
   * and the check costs one plex.tv call per viewer per day.
   */
  async function revalidate(sid: string, uid: string, token: string): Promise<boolean> {
    const stored = db.getSession(sid);
    if (!stored) return false;
    if (now() - stored.lastValidatedAt < cfg.revalidateAfterMs) return true;

    const resources = await fetchResources(token, identity);
    if (!grantsAccessTo(resources, cfg.plexMachineId)) {
      // Every session this person holds goes, not just the one that happened to
      // make this request — otherwise their other tab keeps working.
      db.deleteSessionsForUser(uid);
      return false;
    }
    db.touchSession(sid, now());
    return true;
  }

  return async function handle(req: IncomingMessage, res: ServerResponse): Promise<void> {
    const url = new URL(req.url || '/', 'http://localhost');
    const path = url.pathname;

    try {
      // ── Unauthenticated ────────────────────────────────────────────────────

      if (path === '/healthz') {
        return json(res, 200, { ok: true });
      }

      // Served unauthenticated because the sign-in page itself needs it, and a
      // display face is not a secret.
      if (path === '/signin/archivo-black.ttf') {
        const font = archivoBlack();
        if (!font) return json(res, 404, { error: 'not found' });
        res.writeHead(200, {
          'content-type': 'font/ttf',
          'content-length': font.length,
          'cache-control': 'public, max-age=31536000, immutable',
        });
        res.end(font);
        return;
      }

      // The link-preview card, for crawlers that have no Plex account and
      // never will (see shareTags in signin-page.ts). Cached hard: unfurlers
      // refetch it far more often than it changes, and it is a fixed asset.
      if (path === '/signin/share.png') {
        const card = shareCard();
        if (!card) return json(res, 404, { error: 'not found' });
        res.writeHead(200, {
          'content-type': 'image/png',
          'content-length': card.length,
          'cache-control': 'public, max-age=86400',
          'x-content-type-options': 'nosniff',
        });
        res.end(card);
        return;
      }

      // ── First run ──────────────────────────────────────────────────────
      //
      // Until a Plex server is chosen there is nothing to check anyone against,
      // so these are open by necessity. The setup CODE is what stands in for a
      // session: it is printed to the container log, so producing it proves
      // control of the host, which is exactly the claim being made.
      if (!isConfigured(inst)) {
        if (path === '/setup' || (path === '/' && req.method === 'GET')) {
          return html(res, 200, setupPage());
        }

        if (path === '/setup/claim' && req.method === 'POST') {
          const body = await readJsonBody(req) as { token?: string };
          const given = String(body?.token ?? '').trim().toLowerCase();
          const expected = (inst.setupToken || '').toLowerCase();
          // Length-checked before compare so a wrong-length guess cannot throw.
          const ok = expected.length > 0 && given.length === expected.length
            && timingSafeEqual(Buffer.from(given), Buffer.from(expected));
          if (!ok) return json(res, 403, { error: 'That setup code is not right. Check the container log.' });
          setupClaimed = true;
          return json(res, 200, { ok: true });
        }

        if (path === '/setup/claim-pin' && req.method === 'POST') {
          if (!setupClaimed) return json(res, 403, { error: 'Enter the setup code first.' });
          const body = await readJsonBody(req) as { id?: number };
          const id = Number(body?.id);
          if (!Number.isFinite(id) || !pendingPins.has(id)) {
            return json(res, 400, { error: 'unknown or expired sign-in' });
          }
          const tok = await claimPin(id, identity);
          if (!tok) return json(res, 202, { pending: true });
          pendingPins.delete(id);
          setupToken = tok;
          // Only servers this account OWNS. You cannot point the store at
          // somebody else's library, and gating on a server you do not own
          // would hand its owner the ability to lock you out by unsharing.
          const resources = await fetchResources(tok, identity);
          const servers = (Array.isArray(resources) ? resources : [])
            .filter((r) => r && r.owned === true && typeof r.provides === 'string'
              && r.provides.split(',').some((x: string) => x.trim() === 'server'))
            .map((r) => ({ id: String(r.clientIdentifier), name: String((r as { name?: string }).name || 'Plex Server') }));
          return json(res, 200, { servers });
        }

        if (path === '/setup/finish' && req.method === 'POST') {
          if (!setupClaimed || !setupToken) return json(res, 403, { error: 'Start setup again.' });
          const body = await readJsonBody(req) as { machineId?: string };
          const machineId = String(body?.machineId ?? '').trim();
          // Re-verify against Plex rather than trusting the posted id: the
          // browser could send anything, and this is the one write that decides
          // what the whole gate checks against forever after.
          const resources = await fetchResources(setupToken, identity);
          const owns = resources.some((r) => r && r.clientIdentifier === machineId && r.owned === true);
          if (!machineId || !owns) return json(res, 403, { error: 'You do not own that server.' });

          inst.plexMachineId = machineId;
          inst.setupToken = null;   // single use, and the surface closes with it
          cfg.plexMachineId = machineId;
          saveInstance(cfg.databasePath, inst);
          setupToken = null;
          console.log(`[front-door] setup complete — gating Plex server ${machineId}`);
          return json(res, 200, { ok: true });
        }

        if (path === '/healthz') return json(res, 200, { ok: true, setup: 'pending' });
        if (path === '/signin/archivo-black.ttf') { /* fall through to the font route */ }
        else if (path !== '/auth/pin') {
          return json(res, 503, { error: 'This store has not been set up yet.' });
        }
      }

      // Begin sign-in. Deliberately reachable without a session — it is how you
      // get one — so it is the most exposed endpoint in the service.
      if (path === '/auth/pin' && req.method === 'POST') {
        // Sweep expired pins on the way in. Cheap, and it keeps an unbounded map
        // from being an easy memory-exhaustion target.
        for (const [id, p] of pendingPins) {
          if (now() - p.createdAt > PIN_TTL_MS) pendingPins.delete(id);
        }
        if (rateLimited(req, now())) {
          return json(res, 429, { error: 'too many sign-in attempts, try again shortly' });
        }
        if (pendingPins.size > 100) {
          return json(res, 429, { error: 'too many sign-ins in flight, try again shortly' });
        }
        const pin = await createPin(identity);
        pendingPins.set(pin.id, { createdAt: now() });
        return json(res, 200, { id: pin.id, code: pin.code, authUrl: pin.authUrl });
      }

      // Exchange an authorised pin for a session. THIS is where the gate runs.
      if (path === '/auth/claim' && req.method === 'POST') {
        const body = await readJsonBody(req) as { id?: number; aspect?: string };
        const id = Number(body?.id);
        if (!Number.isFinite(id) || !pendingPins.has(id)) {
          return json(res, 400, { error: 'unknown or expired sign-in' });
        }

        const token = await claimPin(id, identity);
        if (!token) return json(res, 202, { pending: true });
        pendingPins.delete(id);

        const [account, resources] = await Promise.all([
          fetchAccount(token, identity),
          fetchResources(token, identity),
        ]);
        if (!account) return json(res, 502, { error: 'could not read your Plex account' });

        // The gate. A valid Plex login is NOT enough — anyone can make a Plex
        // account. This asks whether the owner shared this server with them.
        if (!grantsAccessTo(resources, cfg.plexMachineId)) {
          return json(res, 403, {
            error: 'This store is limited to people with access to its Plex library. '
              + 'Ask the owner to share a library with your Plex account.',
          });
        }

        const owner = isOwnerOf(resources, cfg.plexMachineId);
        db.upsertUser(account.id, account.username, owner, now());
        const sid = db.createSession(account.id, token, owner, now(), body?.aspect);
        const exp = now() + cfg.sessionTtlMs;
        setSessionCookie(req, res, signSession({ sid, uid: account.id, owner, exp }, cfg.sessionSecret), cfg.sessionTtlMs);
        return json(res, 200, { ok: true, username: account.username, owner });
      }

      // ── Authenticated ──────────────────────────────────────────────────────

      const session = currentSession(req);

      if (path === '/auth/signout' && req.method === 'POST') {
        if (session) {
          db.deleteSession(session.payload.sid);
          // Otherwise a token for a signed-out session lingers in memory and
          // would be handed to the next holder of that session id.
          connCache.delete(session.payload.sid);
        }
        clearSessionCookie(req, res);
        // The holding page signs out with a plain <form>, so a browser needs a
        // redirect; fetch callers still get JSON.
        if ((req.headers.accept || '').includes('text/html')) {
          res.writeHead(303, { location: '/' });
          res.end();
          return;
        }
        return json(res, 200, { ok: true });
      }

      if (!session) {
        if (path.startsWith('/api/')) return json(res, 401, { error: 'sign in first' });
        // A browser gets the gate, not a JSON error. 200 rather than 401
        // because this IS the page for this request, not a failure to render
        // one — a 401 with a body makes some clients show their own auth UI.
        return html(res, 200, signInPage(publicOrigin(req)));
      }

      const { payload, token } = session;
      if (!(await revalidate(payload.sid, payload.uid, token))) {
        clearSessionCookie(req, res);
        return json(res, 403, { error: 'your access to this Plex library was removed' });
      }

      // Owner-only status page, reachable deliberately rather than by landing
      // on it. Says who you are and whether the store is up.
      if (path === '/whoami' && req.method === 'GET') {
        const stored = db.getSession(payload.sid);
        return html(res, 200, signedInPage(stored?.uid ?? payload.uid, payload.owner));
      }

      // Reachable from the store: the power menu's project row is repointed
      // here by the bootstrap, and it is a plain link so it works with no
      // script at all.
      if (path === '/signout') {
        db.deleteSession(payload.sid);
        connCache.delete(payload.sid);
        clearSessionCookie(req, res);
        res.writeHead(303, { location: '/' });
        res.end();
        return;
      }

      if (path === '/api/me') {
        return json(res, 200, { uid: payload.uid, owner: payload.owner });
      }

      if (path === '/api/config' && req.method === 'GET') {
        return json(res, 200, db.getConfig(payload.uid));
      }

      if (path === '/api/config' && req.method === 'PUT') {
        const body = await readJsonBody(req) as { key?: string; value?: string | null };
        const key = String(body?.key ?? '');

        // Server-side enforcement. The drawer also hides owner-only rows, but
        // this endpoint is one fetch away and a hidden control is not a control.
        const verdict = assertWritable(key, payload.owner);
        if (!verdict.ok) return json(res, 403, { error: verdict.reason });

        // null CLEARS. Absence is meaningful in this app's config model — a
        // library switched back on is expressed by deleting its key, so an
        // empty-string write would not mean the same thing.
        if (body?.value === null || body?.value === undefined) {
          db.clearConfig(payload.uid, key);
        } else {
          db.setConfig(payload.uid, key, String(body.value), now());
        }
        return json(res, 200, { ok: true });
      }

      // Everything else is the store itself, proxied from the app process on
      // loopback. Reaching this line means the request already carried a valid,
      // re-validated session — which is the whole point: the store is not
      // served on a port of its own, so there is no way to reach it that
      // bypasses the gate.
      //
      // NOTE this proxies ONE SHARED store to every viewer. Per-user rendering
      // instances (Phase 2) replace it; until then everyone drives the same
      // camera and rendering happens in the viewer's own browser.
      // Only the DOCUMENT is rewritten. Assets stream through untouched, and
      // resolving a connection costs a plex.tv round trip we should not pay on
      // every texture.
      let bootstrap: string | undefined;
      if ((req.headers.accept || '').includes('text/html')) {
        const conn = await connectionFor(payload.sid, token);
        // No connection is not an error. It means this viewer can sign in but
        // cannot currently reach the server — sharing revoked between checks, or
        // Plex not answering. The store then shows its own setup terminal, which
        // is a worse experience than a stocked store and a much better one than
        // a blank screen.
        // Store policy rides along with the connection: which libraries this
        // store carries and whether the games department exists are the
        // owner's decisions, applied to every viewer on every load. Written as
        // the app's OWN settings keys, so the store needs no knowledge of a
        // front door to obey them.
        if (conn) bootstrap = connectionBootstrapScript(conn, payload.uid, policyKeys(loadPolicy(db)));
      }
      proxyToApp(req, res, cfg.appOrigin, bootstrap);
      return;
    } catch (err) {
      // Never leak an internal error to a public caller: the message could name
      // a path, a query or a token. Log it, answer with nothing.
      const ref = randomUUID().slice(0, 8);
      console.error(`[front-door] ${ref}`, err);
      return json(res, 500, { error: 'something went wrong', ref });
    }
  };
}

/** Entry point. Only runs when this module is executed directly. */
export function main(): void {
  const { cfg, instance } = loadConfig();
  const db = new FrontDoorStore(cfg.databasePath, cfg.tokenKey);
  // Say where state lives, every boot. "I can't see any app data" is otherwise
  // impossible to answer from the outside: a Docker named volume is under
  // /var/lib/docker/volumes and invisible to a NAS file browser, and a wrong
  // DATABASE_PATH writes inside the container where it dies with it. One line
  // of log turns that into something checkable.
  console.log(`[front-door] state: ${cfg.databasePath} (+ instance.json beside it)`);
  const handler = createFrontDoor(cfg, db, Date.now, instance);
  startAdminServer(cfg, db, instance, {
    clientId: process.env.PLEX_CLIENT_ID || instance.plexClientId,
    product: process.env.PLEX_PRODUCT || 'VolkBuster Video',
    version: '0.15.0',
    device: 'VolkBuster Front Door',
    platform: 'Node',
  });
  createServer((req, res) => { void handler(req, res); }).listen(cfg.port, () => {
    if (isConfigured(instance)) {
      console.log(`[front-door] listening on :${cfg.port}, gating Plex server ${instance.plexMachineId}`);
      return;
    }
    // The setup code goes to the log on purpose: reading it is what proves
    // control of the host, and it is the only thing standing between a
    // brand-new store and whoever finds the address first.
    console.log('');
    console.log('  ┌────────────────────────────────────────────────────────┐');
    console.log('  │  VolkBuster Video is not set up yet.                   │');
    console.log('  │                                                        │');
    console.log(`  │  Open  http://<this-host>:${String(cfg.port).padEnd(28)}│`);
    console.log(`  │  Setup code:  ${String(instance.setupToken).padEnd(41)}│`);
    console.log('  │                                                        │');
    console.log('  │  Secrets were generated automatically and stored        │');
    console.log('  │  beside the database. Nothing to configure by hand.     │');
    console.log('  └────────────────────────────────────────────────────────┘');
    console.log('');
  });
}

// `node server/index.ts` runs the service; importing it (tests) does not.
if (process.argv[1] && process.argv[1].endsWith('server/index.ts')) main();
