// Shipped-fallback KTX2 (GPU block-compressed) textures for
// public/textures/surfaces/*/*.ktx2 — the shipped-default step of the
// surface-PBR resolution chain in src/user-assets.ts:
//
//   user-assets PNG drop-in  >  shipped .ktx2  >  shipped .png  >  procedural
//
// The .ktx2 files sit next to their .png source (generated by the PRIVATE
// tools/encode-surfaces.mjs, not run at build time — see that script's
// header for the encode recipe) and carry the exact same pixels as UASTC,
// which three's KTX2Loader transcodes into whatever block-compressed format
// the GPU/driver actually supports (BC7/ASTC/ETC2/...). That format STAYS
// compressed in VRAM, unlike a runtime-decoded PNG which uploads as full
// RGBA8 — the 4-6x memory win the KTX2 conversion task exists for. The PNGs
// remain the source of truth and the runtime fallback: any failure here
// (renderer not registered yet, transcoder init failure, 404, bad transcode)
// falls straight through to the existing PNG loader with a console.warn —
// never a black surface.
//
// The basis transcoder (WASM + JS wrapper) is served locally from
// public/basis/ — copied verbatim from node_modules/three/examples/jsm/libs
// /basis/ (part of the three.js distribution, fine to commit; no CDN).
import * as THREE from 'three';
import { KTX2Loader } from 'three/examples/jsm/loaders/KTX2Loader.js';
import { assetUrl } from './asset-url';

const ktx2Loader = new KTX2Loader();
ktx2Loader.setTranscoderPath(assetUrl('basis/'));

// False until a renderer has been registered AND detectSupport() succeeded.
// Every KTX2 attempt before then (e.g. any surface load that races the
// renderer's own construction) short-circuits straight to the PNG path
// rather than throwing — KTX2Loader.load() throws synchronously if
// detectSupport() hasn't run yet.
let ready = false;

/**
 * Wire the KTX2 transcoder to the live renderer, mirroring the
 * setUploadRenderer registration pattern in poster-textures.ts. Must run
 * before any surface texture load for the KTX2 path to engage that boot —
 * called once from three-scene.ts right where setUploadRenderer already is.
 */
export function setSurfaceKtx2Renderer(renderer: THREE.WebGLRenderer): void {
  try {
    ktx2Loader.detectSupport(renderer);
    ready = true;
  } catch (err) {
    console.warn('[surface-textures] KTX2Loader.detectSupport failed; shipped surfaces will use PNG:', err);
    ready = false;
  }
}

/**
 * Attempt the shipped KTX2 sibling of a shipped surface PNG. `relPath` is
 * the same 'surfaces/<dir>/<map>.png' path tryLoadUserAssetTexture already
 * resolves for the PNG step; this swaps in '.ktx2' and tries that first.
 * `onMiss` is the caller's PNG-path continuation — invoked (with a
 * console.warn) on ANY failure so a bad/missing/unsupported KTX2 never
 * blanks a surface, it just costs the PNG's extra VRAM for that map.
 */
export function tryLoadShippedSurfaceKtx2(
  relPath: string,
  onLoad: (tex: THREE.Texture) => void,
  srgb: boolean,
  onMiss: () => void,
): void {
  if (!ready) { onMiss(); return; }
  const ktx2RelPath = relPath.replace(/\.png$/, '.ktx2');
  const url = assetUrl(`textures/${ktx2RelPath}`);
  try {
    ktx2Loader.load(
      url,
      (tex) => {
        // Force the exact colorSpace convention the PNG path uses (see
        // loadOne in user-assets.ts) instead of trusting the KTX2 file's own
        // DFD-derived tag, so the two paths are behaviourally identical to
        // every caller (store-shell.ts, exterior-environment.ts, ...).
        tex.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
        // KTX2Loader already sets these from the file's baked mip chain, but
        // pin them explicitly: KTX2 carries the full mip chain baked in, so
        // generateMipmaps must stay false and the min filter must stay
        // trilinear (LinearMipmapLinearFilter), exactly what encode-surfaces
        // .mjs's --genmipmap chain is for.
        tex.generateMipmaps = false;
        if (tex.mipmaps && tex.mipmaps.length > 1) {
          tex.minFilter = THREE.LinearMipmapLinearFilter;
        }
        tex.magFilter = THREE.LinearFilter;
        onLoad(tex);
      },
      undefined,
      (err) => {
        console.warn(`[surface-textures] KTX2 load failed for ${url}, falling back to PNG:`, err);
        onMiss();
      },
    );
  } catch (err) {
    // Defensive: setSurfaceKtx2Renderer/`ready` should prevent ever reaching
    // here, but a throw must never propagate out and blank a surface.
    console.warn(`[surface-textures] KTX2Loader.load threw for ${url}, falling back to PNG:`, err);
    onMiss();
  }
}
